from django.test import TestCase
from django.contrib.auth.models import User


from .models import Post



class BlogTests(TestCase):
    @classmethod
    def setUpTestData(cls):
        # Create User
        testuser1 = User.objects.create_user(
            username='testuser1', 
            password='123testpassw'
        )
        testuser1.save()

        #Create Blog
        test_post = Post.objects.create(
            author=testuser1,
            title='Test Blog Title',
            body='Blog post content generated by automated test...'
        )
        test_post.save()


    def test_blog_content(self):
        post = Post.objects.get(id=1)
        author = f'{post.author}'
        title = f'{post.title}'
        body = f'{post.body}'
        self.assertEqual(author, 'testuser1')
        self.assertEqual(title, 'Test Blog Title')
        self.assertEqual(body, 'Blog post content generated by automated test...')